version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-album
    environment:
      MYSQL_DATABASE: album
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  minio:
    image: minio/minio
    container_name: minio-album
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"