server:
  port: 8081
  servlet:
    context-path: /projeto-album
spring:
  application:
    name: album
  datasource:
    url: jdbc:mysql://localhost:3307/album?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect : org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

